### ISSUE TITLE
Sanity edit event description into rich text block

### ISSUE THREAD

**Issue by lovisegit** [oslopride/skeivt-kulturaar#37]
Kan vi endre slik at feltet med event beskrivelse blir en rich text block. Eller wysiwyg? 

Slik er den i dag: 
<img width="653" alt="Skjermbilde 2022-02-02 kl  18 14 19" src="https://user-images.githubusercontent.com/93185620/152203647-63c7c7eb-fe3d-46d1-841f-a676624a7026.png">

**Comment by hexjelly** [comment]
Changed to "text" instead of "string" type. I think a rich content block will cause too many headaches, both with form submission and offering the content in an API later for external users. Can revisit if super important later?
